name: Deploy to HF Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs track "*.csv"
          git add .gitattributes
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit -m "track csv with lfs" || echo "nothing to commit"

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push -f https://Rashmiprakash-56:$HF_TOKEN@huggingface.co/spaces/Rashmiprakash78/electricity_demand_backend main