name: Deploy to HF Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
        run: |
          git push -f https://Rashmiprakash-56:$HF_TOKEN@huggingface.co/spaces/Rashmiprakash78/electricity_demand_backend main
